Introduced PR templates
hasura/learn-graphql pull request #795
Opened 2022-10-27 14:59 UTC by koconder

Fixes #786

Based on main repo PR template, see: https://github.com/hasura/graphql-engine/blob/master/.github/PULL_REQUEST_TEMPLATE.md

2023-01-22 01:21 UTC, koconder commented
@NoriSte @andoks @praveenweb quick one to close #786

2023-01-23 07:56 UTC, NoriSte commented
I'd like to get a review from @praveenweb since he has more context about the whole product (since I have comprehension for the Console part only).

And, of course, thank you so much @koconder 😊 I'll send it to Praveen directly 😊

2023-01-23 09:19 UTC, praveenweb commented on PULL_REQUEST_TEMPLATE.md
> +### Changelog
In the learn course template, we don't have versions or changelog. Can we remove this section?

2023-01-23 09:19 UTC, praveenweb commented on PULL_REQUEST_TEMPLATE.md
> +#### Breaking changes
Similarly, there are no breaking changes applicable.

2023-01-23 09:20 UTC, praveenweb requested changes
Added comments to remove a couple of sections

2023-01-23 10:50 UTC, koconder commented
@praveenweb changes made as requested

2023-01-30 10:19 UTC, merged